src/Entity/Theme.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ThemeRepository")
 */
class Theme
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Produit", mappedBy="theme")
     */
    private $produit;

    public function __construct()
    {
        $this->produit = new ArrayCollection();
    }



    public function getID(): ?string
    {
        return $this->id;
    }


    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    /**
     * @return Collection|Produit[]
     */
    public function getProduit(): Collection
    {
        return $this->produit;
    }

    public function addProduit(Produit $produit): self
    {
        if (!$this->produit->contains($produit)) {
            $this->produit[] = $produit;
            $produit->setTheme($this);
        }

        return $this;
    }

    public function removeProduit(Produit $produit): self
    {
        if ($this->produit->contains($produit)) {
            $this->produit->removeElement($produit);
            // set the owning side to null (unless already changed)
            if ($produit->getTheme() === $this) {
                $produit->setTheme(null);
            }
        }

        return $this;
    }

}

templates/index/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Somadala{% endblock %}
{% block stylesheets %}
    <link href="/Css/index.css" rel="stylesheet">
{% endblock %}

{% block body %}
    <header class="container-fluid">
        <div class="head d-flex">
            <div class="align-self-center w-100">
                <div class="text-center mx-auto title">
                    <div class="card">
                        <h1 class="Maintitle">SOMADALA</h1>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
        <div class="container">
            <a class="navbar-brand font-weight-lighter" href="#">Somadala</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    {% if app.user %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ path("client_showme")}}"><i class="far fa-user"> Profile</i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ path("panier_showMonPanier") }}"><i class="fas fa-shopping-cart"> Panier</i></a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path("questions_index") }}"><i class="far fa-comments"> FAQ</i></a>
                    </li>
                </ul>

                <div class="my-2 my-lg-0">
                    {% if not app.user %}
                        <a class="btn btn-outline-success my-2 my-sm-0" href="{{path('security_login')}}">Connexion</a>
                        <a class="btn btn-outline-success my-2 my-sm-0" href="{{path('security_registration')}}">Inscription</a>
                    {% else %}
                        <a class="btn btn-outline-success my-2 my-sm-0" href="{{path('security_logout')}}">Deconnexion</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>



    <div class="container-fluid mt-5">
        <div class="container">
            <div class="card">
                <h2 class="Subtitle m-0 text-center"> <img src="/Image/Logo.svg" class="w-10">LES CREATIONS</h2>
            </div>
            {% if is_granted('ROLE_ADMIN') %}
                <a  class="btn btn-primary" href="{{ path('theme_new')}}"><i class="fas fa-pen"></i> Ajouter un thème</a>
                <a  class="btn btn-primary" href="{{ path('produit_new')}}"><i class="fas fa-pen"></i> Ajouter un produit</a>
            {% endif %}
        </div>
        <div class="container mt-5">
            <div class="jumbotron">
                {{ form_start(form) }}
                <div class="form-row">
                    <div class="col">
                        {{ form_row(form.maxPrix) }}
                    </div>
                    <div class="col">
                        {{ form_row(form.minPrix) }}
                    </div>
                    <div class="col">
                        {{ form_row(form.nom) }}
                    </div>
                    <div class="col">
                        {{ form_row(form.theme) }}
                    </div>
                    <div class="col">
                        <button class="btn btn-primary">Rechercher</button>
                    </div>
                </div>
                {{ form_end(form) }}
            </div>
            <div class="row">
                {% for product in products %}
                    <div class="col-4 mt-5 ">
                        {%  include "shared/card.html.twig" %}
                    </div>
                {% endfor %}
                <div class="col-12">
                    <div class="pagination">
                        {{ knp_pagination_render(products) }}
                    </div>
                </div>
            </div>
        </div>

        <div class="container mt-5">
            <div class="card">
                <h2 class="Subtitle m-0 text-center"> <img src="/Image/Logo.svg" class="w-10">NOUS CONTACTER</h2>
            </div>
        </div>
        <div class="container mt-5">
            <div class="row">
                <div class="col-6">
                    <iframe width="100%" height="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.openstreetmap.org/export/embed.html?bbox=6.601350903511048%2C47.06206841656023%2C6.607144474983216%2C47.0644911438875&amp;layer=mapnik&amp;marker=47.06327979398653%2C6.604247689247131" style="border: 1px solid black"></iframe><br/><small><a href="https://www.openstreetmap.org/?mlat=47.06328&amp;mlon=6.60425#map=18/47.06328/6.60425">Afficher une carte plus grande</a></small>
                </div>
                <div class="col-6">

                    <p class="font-weight-lighter">
                        Intellectum est enim mihi quidem in multis, et maxime in me ipso, sed paulo ante in omnibus, cum M.
                        Marcellum senatui reique publicae concessisti, commemoratis praesertim offensionibus, te auctoritatem huius
                        ordinis dignitatemque rei publicae tuis vel doloribus vel suspicionibus anteferre.
                    </p>
                    {{ form_start(formContact) }}
                    <div class="mb-3">
                        {{ form_row(formContact.nom,{'label':false,'attr':{'placeholder':'Votre nom','class':'form-control border-orange','aria-label':'Username','aria-describedby':'nom'}}) }}
                    </div>
                    <div class="mb-3">
                        {{ form_row(formContact.prenom,{'label':false,'attr':{'placeholder':'Votre prénom','class':'form-control border-orange','aria-label':'Username','aria-describedby':'nom'}}) }}
                    </div>
                    <div class="mb-3">
                        {{ form_row(formContact.telephone,{'label':false,'attr':{'placeholder':'Votre téléphone','class':'form-control border-orange','aria-label':'Username','aria-describedby':'nom'}}) }}
                    </div>
                    <div class="mb-3">
                        {{ form_row(formContact.mail,{'label':false,'attr':{'placeholder':'Votre mail','class':'form-control border-orange','aria-label':'Username','aria-describedby':'nom'}}) }}
                    </div>
                    <div class="mb-3">
                        {{ form_row(formContact.sujet,{'label':false,'attr':{'placeholder':'Sujet de votre message','class':'form-control border-orange','aria-label':'Username','aria-describedby':'nom'}}) }}
                    </div>
                    <div class="mb-3">
                        {{ form_row(formContact.message,{'label':false,'attr':{'placeholder':'Votre message','class':'form-control border-orange','aria-label':'Username','aria-describedby':'nom'}}) }}
                    </div>
                    <button class="btn btn-orange">Envoyer</button>
                    {{ form_end(formContact) }}
                </div>
            </div>
        </div>
        <div class="container mt-5">
            <div class="card">
                <h2 class="Subtitle m-0 text-center"> <img src="/Image/Logo.svg" class="w-10">A PROPOS</h2>
            </div>
        </div>
        <div class="container mt-3">
            <div class="row">
                <div class="col-6">
                    <p class="font-weight-lighter">
                        Intellectum est enim mihi quidem in multis, et maxime in me ipso, sed paulo ante in omnibus, cum M.
                        Marcellum senatui reique publicae concessisti, commemoratis praesertim offensionibus, te auctoritatem huius
                        ordinis dignitatemque rei publicae tuis vel doloribus vel suspicionibus anteferre.
                        Ille quidem fructum omnis ante actae vitae hodierno die maximum cepit, cum summo consensu senatus,
                        tum iudicio tuo gravissimo et maximo. Ex quo profecto intellegis quanta in dato beneficio sit laus,
                        cum in accepto sit tanta gloria.
                    </p>
                </div>
                <div class="col-6">
                    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <img src="/Image/Logo.svg" class="d-block w-100" alt="...">
                            </div>
                            {% for product in products %}
                                <div class="carousel-item">
                                    <img src="{{product.image}}" class="d-block w-100" alt="...">
                                </div>
                            {% endfor %}
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer class="mt-5 footheight text-center">
        <div class="row">
            <div class="col-4">
                Somadala
            </div>
            <div class="col-4">
                <img src="/Image/Logo.svg" class="w-10">
            </div>
            <div class="col-4">
                <b>Allard Nathanael | Symfony </b>
            </div>
        </div>
    </footer>


{% endblock %}