src/Entity/Client.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;



/**
 * @ORM\Entity(repositoryClass="App\Repository\ClientRepository")
 * @UniqueEntity(
 *     fields={"mail"},
 *     message="L'utilisateur existe déja"
 * )
 */
class Client implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $code_postal;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $mail;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=8, minMessage="Votre mot de passe doit faire au moins 8 caractères")
     */
    private $mdp;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $telephone;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Panier", mappedBy="client_id", cascade={"persist", "remove"})
     */
    private $panier;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $roles;

    private $rolesToSting;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Questions", mappedBy="client")
     */
    private $questions;

    public function __construct()
    {
        $this->questions = new ArrayCollection();
    }


    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getMdp(): ?string
    {
        return $this->mdp;
    }

    public function setMdp(string $mdp): self
    {
        $this->mdp = $mdp;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getPanier(): ?Panier
    {
        return $this->panier;
    }

    public function setPanier(?Panier $panier): self
    {
        $this->panier = $panier;

        // set (or unset) the owning side of the relation if necessary
        $newClient_id = null === $panier ? null : $this;
        if ($panier->getClientId() !== $newClient_id) {
            $panier->setClientId($newClient_id);
        }

        return $this;
    }



    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }
    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }
    public function getRoles()
    {
        return array($this->roles);
    }

    public function getRolesToString()
    {
        return $this->roles;
    }


    /**
     * @inheritDoc
     */
    public function getPassword()
    {
        return $this->mdp;
    }

    /**
     * @inheritDoc
     */
    public function getUsername()
    {
        return $this->nom;
    }

    public function setRoles(string $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function setRolesToString(string $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function getId()
    {
        return $this->id;
    }

    /**
     * @return Collection|Questions[]
     */
    public function getQuestions(): Collection
    {
        return $this->questions;
    }

    public function addQuestion(Questions $question): self
    {
        if (!$this->questions->contains($question)) {
            $this->questions[] = $question;
            $question->setClient($this);
        }

        return $this;
    }

    public function removeQuestion(Questions $question): self
    {
        if ($this->questions->contains($question)) {
            $this->questions->removeElement($question);
            // set the owning side to null (unless already changed)
            if ($question->getClient() === $this) {
                $question->setClient(null);
            }
        }

        return $this;
    }




}

src/Form/ClientType.php
<?php

namespace App\Form;

use App\Entity\Client;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ClientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('adresse')
            ->add('code_postal')
            ->add('ville')
            ->add('mail')
            ->add('mdp', PasswordType::class)
            ->add('telephone')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Client::class,
        ]);
    }
}

src/Controller/ClientController.php
<?php

namespace App\Controller;

use App\Entity\Client;
use App\Form\ClientType;
use App\Repository\ClientRepository;
use App\Security\Voter\ClientVoter;
use App\Security\Voter\ProfileVoter;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * @Route("/client")
 */
class ClientController extends AbstractController
{
    /**
     * @IsGranted("ROLE_ADMIN")
     * @Route("/", name="client_index", methods={"GET"})
     */
    public function index(ClientRepository $clientRepository): Response
    {
        return $this->render('client/index.html.twig', [
            'clients' => $clientRepository->findAll(),
        ]);
    }

    /**
     * @Route("/monprofil", name="client_showme")
     */
    public function showmonprofil(): Response
    {
        $client = $this->getUser();

        return $this->render('client/show.html.twig', [
            'client' => $client,
        ]);
    }

    /**
     * @IsGranted("ROLE_ADMIN")
     * @Route("/{id}", name="client_show", methods={"GET"})
     */
    public function show(Client $client): Response
    {
        return $this->render('client/show.html.twig', [
            'client' => $client,
        ]);
    }

    /**
     * @Route("/edit/monprofil", name="client_edit")
     */
    public function edit(Request $request,UserPasswordEncoderInterface $encoder): Response
    {
        $client = $this->getUser();
        $this->denyAccessUnlessGranted(ProfileVoter::PROFIL_EDIT,$client);

        $form = $this->createForm(ClientType::class, $client);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $hash = $encoder->encodePassword($client, $client->getMdp());
            $client->setMdp($hash);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($client);
            $entityManager->flush();

            return $this->redirectToRoute('index');
        }

        return $this->render('client/edit.html.twig', [
            'client' => $client,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @IsGranted("ROLE_ADMIN")
     * @Route("/{id}", name="client_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Client $client): Response
    {
        if ($this->isCsrfTokenValid('delete'.$client->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($client);
            $entityManager->flush();
        }

        return $this->redirectToRoute('client_index');
    }
}

templates/client/_delete_form.html.twig
<form method="post" action="{{ path('client_delete', {'id': client.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ client.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/client/_form.html.twig
{{ form_start(form) }}
<div class="input-group mb-3">
    <div class="input-group-prepend">
        <span class="input-group-text" id="nom">Votre nom</span>
    </div>
    {{ form_row(form.nom,{'label':false,'attr':{'placeholder':'Nom d utilisateur','class':'form-control','aria-label':'Username','aria-describedby':'nom'}}) }}
</div>

<div class="input-group mb-3">
    <div class="input-group-prepend">
        <span class="input-group-text" id="prenom">Votre prénom</span>
    </div>
    {{ form_row(form.prenom,{'label':false,'attr':{'placeholder':'Prénom d utilisateur','class':'form-control','aria-label':'Username','aria-describedby':'prenom'}}) }}
</div>

<div class="input-group mb-3">
    <div class="input-group-prepend">
        <span class="input-group-text" id="adresse">Votre adresse</span>
    </div>
    {{ form_row(form.adresse,{'label':false,'attr':{'placeholder':'Nom d utilisateur','class':'form-control','aria-label':'Username','aria-describedby':'adresse'}}) }}
</div>

<div class="input-group mb-3">
    <div class="input-group-prepend">
        <span class="input-group-text" id="postal">Votre code postal</span>
    </div>
    {{ form_row(form.code_postal,{'label':false,'attr':{'placeholder':'Nom d utilisateur','class':'form-control','aria-label':'Username','aria-describedby':'postal'}}) }}
</div>
<div class="input-group mb-3">
    <div class="input-group-prepend">
        <span class="input-group-text" id="ville">Votre ville</span>
    </div>
    {{ form_row(form.ville,{'label':false,'attr':{'placeholder':'Nom d utilisateur','class':'form-control','aria-label':'Username','aria-describedby':'ville'}}) }}
</div>
<div class="input-group mb-3">
    <div class="input-group-prepend">
        <span class="input-group-text" id="mdp">Votre mot de passe</span>
    </div>
    {{ form_row(form.mdp,{'label':false,'attr':{'placeholder':'Nom d utilisateur','type':'password','class':'form-control','aria-label':'Username','aria-describedby':'mdp'}}) }}
</div>
<div class="input-group mb-3">
    <div class="input-group-prepend">
        <span class="input-group-text" id="tel">Votre téléphone</span>
    </div>
    {{ form_row(form.telephone,{'label':false,'attr':{'placeholder':'Nom d utilisateur','class':'form-control','aria-label':'Username','aria-describedby':'tel'}}) }}
</div>

<div class="input-group mb-3">
    <div class="input-group-prepend">
        <span class="input-group-text" id="adresse">Votre adresse</span>
    </div>
    {{ form_row(form.mail,{'label':false,'attr':{'placeholder':'Nom d utilisateur','class':'form-control','aria-label':'Username','aria-describedby':'nom'}}) }}
</div>
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/client/edit.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    <link href="/Css/index.css" rel="stylesheet">
{% endblock %}
{% block title %}Edit Client{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="container-fluid">
            <h1 class="text-center">Editer votre profil</h1>
            <div class="row">
                <div class="col-6">
                    <div class="vh-100 d-flex">
                        <div class="align-self-center w-100">
                            <div class="mx-auto w-50">
                                {{ include('client/_form.html.twig', {'button_label': 'Update'}) }}
                                {{ include('client/_delete_form.html.twig') }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-6 fondMandala1">
                </div>
            </div>
         </div>
    </div>

    {% if is_granted('ROLE_ADMIN') %}
        <a href="{{ path('client_index') }}">back to list</a>
    {% endif %}

{% endblock %}

templates/client/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Client index{% endblock %}

{% block body %}
    <h1>Client index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Adresse</th>
                <th>Code_postal</th>
                <th>Ville</th>
                <th>Mail</th>
                <th>Mdp</th>
                <th>Telephone</th>
                <th>Roles</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for client in clients %}
            <tr>
                <td>{{ client.id }}</td>
                <td>{{ client.nom }}</td>
                <td>{{ client.prenom }}</td>
                <td>{{ client.adresse }}</td>
                <td>{{ client.codePostal }}</td>
                <td>{{ client.ville }}</td>
                <td>{{ client.mail }}</td>
                <td>{{ client.mdp }}</td>
                <td>{{ client.telephone }}</td>
                {% for role in client.roles  %}
                    <td>{{ role }}</td>
                {%  endfor%}
                <td>
                    <a href="{{ path('client_show', {'id': client.id}) }}">show</a>
                    <a href="{{ path('client_edit', {'id': client.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/client/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Client{% endblock %}

{% block body %}
    <h1>Create new Client</h1>

    {{ include('client/_form.html.twig') }}
    {% if is_granted('ROLE_ADMIN') %}
        <a href="{{ path('client_index') }}">back to list</a>
    {% endif %}
{% endblock %}

templates/client/show.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    <link href="/Css/index.css" rel="stylesheet">
{% endblock %}

{% block title %}Client{% endblock %}

{% block body %}

    <div class="container-fluid">
        <div class="row">
            <div class="col-6">
                <div class="vh-100 d-flex">
                    <div class="align-self-center w-100">
                        <div class="mx-auto w-50">
                            <h1>
                                {{ client.nom }} {{ client.prenom }}</td>
                            </h1>
                            <ul class="list-group">
                                <li class="list-group-item">Votre nom : {{ client.nom }}</li>
                                <li class="list-group-item">Votre prénom : {{ client.prenom }}</li>
                                <li class="list-group-item">Voter adresse : {{ client.adresse }}</li>
                                <li class="list-group-item">Votre code postal : {{ client.codePostal }}</li>
                                <li class="list-group-item">Votre Ville : {{ client.ville }}</li>
                                <li class="list-group-item">Votre mail : {{ client.mail }}</li>
                                <li class="list-group-item">Votre téléphone : {{ client.telephone }}</li>
                            </ul>
                            <div class="row">
                                <div class="col-6">
                                    <a class="btn btn-primary" href="{{ path('client_edit') }}">Editer</a>
                                    <a class="btn btn-primary mt-2" href="{{ path('index') }}">Revenir à la page principale</a>
                                </div>
                                <div class="col-6">
                                    {{ include('client/_delete_form.html.twig') }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-6 fondMandala2">
                {% if is_granted('ROLE_ADMIN') %}
                    <a href="{{ path('client_index') }}">back to list</a>
                {% endif %}
            </div>
        </div>
    </div>



{% endblock %}